function(bake_wgsl_source OUTPUT_FILE WGSL_FILES_LIST_STR)
    file(WRITE ${OUTPUT_FILE} "// This file is generated by CMake. Do not edit this file!\n\n")
    file(APPEND ${OUTPUT_FILE} "#pragma once\n\n")
    file(APPEND ${OUTPUT_FILE} "namespace nlrs\n{\n")
    string(REPLACE " " ";" WGSL_FILES ${WGSL_FILES_LIST_STR})

    foreach(WGSL_FILE IN LISTS WGSL_FILES)
        file(READ ${CMAKE_SOURCE_DIR}/src/pt/${WGSL_FILE} WGSL_CONTENT)
        string(REPLACE ".wgsl" "" VAR_NAME ${WGSL_FILE})
        string(TOUPPER ${VAR_NAME} VAR_NAME)

        # Split WGSL_CONTENT into chunks. Work-around for C2026 errors in MSVC (single-line string too big).
        string(LENGTH "${WGSL_CONTENT}" CONTENT_LENGTH)
        math(EXPR CONTENT_LENGTH "${CONTENT_LENGTH} - 1")
        set(OFFSET 0)
        set(CHUNK_SIZE 16384)

        file(APPEND ${OUTPUT_FILE} "const char* const ${VAR_NAME}_SOURCE = ")

        while(OFFSET LESS_EQUAL CONTENT_LENGTH)
            math(EXPR END_OFFSET "${OFFSET} + ${CHUNK_SIZE} - 1")
            string(SUBSTRING "${WGSL_CONTENT}" ${OFFSET} ${CHUNK_SIZE} CHUNK)
            file(APPEND ${OUTPUT_FILE} "R\"(${CHUNK})\"")
            math(EXPR OFFSET "${OFFSET} + ${CHUNK_SIZE}")

            if(NOT OFFSET GREATER CONTENT_LENGTH)
                file(APPEND ${OUTPUT_FILE} "\n")
            endif()
        endwhile()

        file(APPEND ${OUTPUT_FILE} ";\n\n")
    endforeach()

    file(APPEND ${OUTPUT_FILE} "} // namespace nlrs\n")
endfunction()

if(CALL_BAKE_WGSL_SOURCE)
    # CMake seems to treat the list as separate arguments, so we need to wrap it in a concatenated string.
    bake_wgsl_source("${OUTPUT_FILE}" "${WGSL_FILES}")
endif()
